export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCHING_RESTAURANTS = 'FETCHING_RESTAURANTS';
export const FINISHED_FETCH_RESTAURANT = 'FINISHED_FETCH_RESTAURANT';
export const SET_PAGE_TOKEN = 'SET_PAGE_TOKEN';
export const FETCH_MORE_RESTAURANTS = 'FETCH_MORE_RESTAURANTS';
